service: wikitranslate

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: eu-west-1

package:
  exclude:
    - doc

functions:
  translate:
    handler: handler.translate
    events:
      - http:
          path: "{fromLang}/{toLang}/{input}"
          method: get
          integration: lambda
          request:
            parameters:
              paths:
                fromLang: true
                toLang: true
                input: true
  langs:
    handler: handler.langs
    events:
      - http:
          path: langs
          method: get
          integration: lambda
