service: wikitranslate

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-2
  profile: serverless
  memorySize: 128

package:
  exclude:
    - doc

functions:
  translate:
    handler: handler.translate
    events:
      - http:
          path: "{fromLang}/{toLang}/{input}"
          method: get
          integration: lambda
          cors: true
          request:
            parameters:
              paths:
                fromLang: true
                toLang: true
                input: true
  langs:
    handler: handler.langs
    events:
      - http:
          path: langs
          method: get
          integration: lambda
          cors: true
